### ISSUE TITLE
Pink door problem?

### ISSUE THREAD

**Issue by Saterrr** [TeamTwilight/twilightforest-fabric#101]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.57.0+1.18.2

### Twilight Forest Version

4.1.232

### Client Log

https://gist.github.com/Saterrr/27dd38410f7eacc2f3960532d8e09b1a

### Crash Report (if applicable)

https://gist.github.com/Saterrr/524e10464b9ab83f84b65d42ce045f69

### Steps to Reproduce

1. Click on the twilight forest mod category
2. Scroll down a bit
3. I think when you encounter the pink door it instantly crashes your minecraft

### What You Expected

I expected for it to just scroll down without crashing.

### What Happened Instead

It crashed while i was scrolling to see new blocks or if you changed textures of some things.

### Additional Details

-- Item being rendered --
Details:
	Item Type: **pink_castle_door**
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:349)
	at net.minecraft.class_918.method_36543(class_918.java:339)
	at net.minecraft.class_918.method_27951(class_918.java:335)
	at net.minecraft.class_465.method_2385(class_465.java:264)
	at net.minecraft.class_465.method_25394(class_465.java:122)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_481.method_25394(class_481.java:679)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Fixed
