### ISSUE TITLE
Issue with Twilightforest and CraftTweaker

### ISSUE THREAD

**Issue by Lancelotth** [TeamTwilight/twilightforest-fabric#118]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.58.0+1.18.2

### Twilight Forest Version

4.1.268

### Steps to Reproduce

1. install Crafttweakers with its dependencies
2. install TwilightForest
3. set up a server and install mods on server
4. try to log in on the server
5. error login in 

### What You Expected

i was expecting to be able to join my server and play modifying recipes. but seems to be a serialization confilct.

### What Happened Instead

trying to join my server got an Exception message.

Exception occurred in netty pipeline io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '29171713' instead.

### Additional Details

[16:06:22] [Netty Client IO #1/ERROR]: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '29171713' instead.
[16:06:22] [Netty Client IO #1/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '29171713' instead.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '29171713' instead.
	at net.minecraft.class_1856.handler$cje000$fromNetwork(class_1856.java:2125) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8141(class_1867.java:113) ~[client-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8122(class_1867.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_17817(class_2788.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.<init>(class_2788.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:471) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.68.Final.jar:?]
	... 36 more
[16:06:22] [Render thread/INFO]: [CHAT] WARNING: Immersive Portals mod is incompatible with mod Twilight Forest(twilightforest) . Major issues will occur. You should uninstall one of the two mods. (If the two mods become compatible now, report it to qouteall.)
[16:06:22] [Netty Client IO #1/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[16:06:22] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld
[16:06:23] [Render thread/INFO]: Clearing audio channels

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
can't reproduce with latest versions
