### ISSUE TITLE
FireReactEnchantment Server Crash

### ISSUE THREAD

**Issue by dandin87** [TeamTwilight/twilightforest-fabric#119]
### Fabric Loader Version

0.14.9

### Fabric API Version

Fabric API 0.58.0+1.18.2

### Twilight Forest Version

4.1.268

### Crash Report (if applicable)

https://aofpaste.com/igunuvaper.yaml

### Steps to Reproduce

Not sure

### What You Expected

No crashy

### What Happened Instead

java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.Entity.isFireImmune()" because "attacker" is null
	at twilightforest.enchantment.FireReactEnchantment.shouldHit(FireReactEnchantment.java:52)
	at twilightforest.enchantment.FireReactEnchantment.onUserDamaged(FireReactEnchantment.java:46)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by dandin87** [comment]
It would seem this is already fixed on Github, but not in the latest release from Curseforge.
