### ISSUE TITLE
Crashing to menu - Error "DataFormatException: Invalid Distance Too Far Back"

### ISSUE THREAD

**Issue by evelyn-loves-coffee** [TeamTwilight/twilightforest-fabric#152]
### Fabric Loader Version

0.14.11

### Fabric API Version

0.69.0+1.19.2

### Twilight Forest Version

4.2.333

### Client Log

https://gist.github.com/evelyn-loves-coffee/39dc59fa1b11f5a8f856ad2eecd29818

### Steps to Reproduce

All of Fabric 6 modpack. Connected to another computer on the same network (started in Singleplayer, then opened to LAN). Crashes as frequent as every 5 minutes, or as little as every hour. No apparent reason for what triggers the crash to menu. Neither of us have traveled to Twilight Forest dimension yet, this is occurring while even just walking around the village where we're playing and not interacting with anything, sometimes with REI open, sometimes without.

### What You Expected

n/a - crashes seemingly without cause.

### What Happened Instead

Crash to menu. In the logs, seeing:
`[21:32:38] [Netty Client IO #5/ERROR]: Twilight Forest: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: invalid distance too far back`

I'm a bit unfamiliar with Java language, mostly work in C#. This may be closest connection to the source of the issue?
`at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]`

### Additional Details

Unsure if combination of REI, AlmostUnified, Twilight Forest is the root cause.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by evelyn-loves-coffee** [comment]
Update:
Another exception which I've seen over the past couple days, in addition to the above and related to Twilight Forest:

Changes in the last 25 minutes:
- Disable Almost Unified, Install Polymorph (Fabric)
- Load game again

Crash after couple minutes:
https://gist.github.com/evelyn-loves-coffee/d4ad51bdb2cd35aa666448274d6071c2

`[10:38:33] [Netty Client IO #13/ERROR]: Twilight Forest: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data`

`Caused by: java.io.IOException: Invalid tag id: 66`

Also to give additional context, the person hosting the singleplayer world which has been opened to LAN, is not getting either of the two issues mentioned in this thread, and has the same modlist for All Of Fabric 6.

**Comment by evelyn-loves-coffee** [comment]
Third error type, no changes made from above:
https://gist.github.com/evelyn-loves-coffee/2319539e13e77b696fc8fbb14212cdd1

`[11:03:13] [Netty Client IO #16/ERROR]: Twilight Forest: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/33 (class_2672) was larger than I expected, found 23733 bytes extra whilst reading packet 33`

**Comment by evelyn-loves-coffee** [comment]
Just to give closure to this issue - I've disabled Twilight Forest from the modpack, yet still getting crashing issues, I believe the errors are misleading and not representative of Twilight Forest, I'm now seeing:

`[12:44:21] [Netty Client IO #6/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[12:44:21] [Netty Client IO #6/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data`

Closing out issue.
