### ISSUE TITLE
Compatibility issue with Immersive Portals

### ISSUE THREAD

**Issue by qouteall** [TeamTwilight/twilightforest-fabric#96]
### Fabric Loader Version

0.14.5

### Fabric API Version

0.56.0+1.18.2

### Twilight Forest Version

4.1

### Steps to Reproduce

Use it with Immersive Portals mod.

### What You Expected

Chunks loaded.

### What Happened Instead

the chunks of twilight forest cannot be loaded on the client, with error
```
 java.lang.IndexOutOfBoundsException: readerIndex(6359) + length(1) exceeds writerIndex(6359): UnpooledHeapByteBuf(ridx: 6359, widx: 6359, cap: 6359/6359)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readByte(FriendlyByteBuf.java:1013) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:344) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readLongArray(FriendlyByteBuf.java:269) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readLongArray(FriendlyByteBuf.java:265) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.PalettedContainer.read(PalettedContainer.java:163) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.read(LevelChunkSection.java:170) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.replaceWithPacketData(LevelChunk.java:445) ~[minecraft-project-@-merged-named.jar:?]
	at qouteall.imm_ptl.core.chunk_loading.MyClientChunkManager.replaceWithPacketData(MyClientChunkManager.java:121) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.updateLevelChunk(ClientPacketListener.java:661) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.handleLevelChunkWithLight(ClientPacketListener.java:656) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:45) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:12) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:22) ~[minecraft-project-@-merged-named.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.lambda$withSwitchedWorld$11(ClientWorldLoader.java:486) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:468) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:485) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
```

### Additional Details

https://github.com/qouteall/ImmersivePortalsMod/issues/1133

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by qouteall** [comment]
Update: I tested the latest Fabric version twilight forest with ImmPtl and the chunk loading issue seems fixed.

But there is a new issue that causes crash:
```
java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract int modifyColor(double, double, int)' of abstract class net.minecraft.world.level.biome.BiomeSpecialEffects$GrassColorModifier.
	at net.minecraft.world.level.biome.Biome.getGrassColor(Biome.java:275)
	at net.minecraft.client.multiplayer.ClientLevel.calculateBlockTint(ClientLevel.java:796)
	at net.minecraft.client.multiplayer.ClientLevel.method_38538(ClientLevel.java:112)
	at net.minecraft.client.color.block.BlockTintCache.getColor(BlockTintCache.java:91)
	at net.minecraft.client.multiplayer.ClientLevel.getBlockTint(ClientLevel.java:778)
	at net.minecraft.client.renderer.chunk.RenderChunkRegion.getBlockTint(RenderChunkRegion.java:67)
	at net.minecraft.client.renderer.BiomeColors.getAverageColor(BiomeColors.java:14)
	at net.minecraft.client.renderer.BiomeColors.getAverageGrassColor(BiomeColors.java:18)
	at net.minecraft.client.color.block.BlockColors.method_1693(BlockColors.java:48)
	at net.minecraft.client.color.block.BlockColors.getColor(BlockColors.java:112)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.putQuadData(ModelBlockRenderer.java:134)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelFaceAO(ModelBlockRenderer.java:120)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:77)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:48)
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.redirect$cbf000$hookChunkBuildTesselate(ChunkRenderDispatcher.java:791)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.compile(ChunkRenderDispatcher.java:578)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.doTask(ChunkRenderDispatcher.java:489)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.method_22757(ChunkRenderDispatcher.java:140)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by AlphaMode** [comment]
![image](https://user-images.githubusercontent.com/26313415/196016407-169ac663-0807-4c7a-8e0d-97082a62ee8e.png)
I can't reproduce this the only issue I'm seeing is IP is completely breaking magic maps

Without IP 
![image](https://user-images.githubusercontent.com/26313415/196016452-2d98144d-d251-496c-8b46-5ec913c24883.png)

With IP
![image](https://user-images.githubusercontent.com/26313415/196016491-1979877e-a813-4d05-940a-942112288b09.png)
